### ISSUE TITLE
Deleting not working

### ISSUE THREAD

**Issue by fanyui** [kefeh/me4real#1]
Deleting any of the resources in the app doesn't work.

**Comment by kefeh** [comment]
I dont think there is a problem with the delete request, you are still not using the correct link. remember you were to send an id in the param and not attach it as a variable to the link

**Comment by fanyui** [comment]
How then should I make the request just provide a template for doing it.

**Comment by kefeh** [comment]
the delete api takes  id as parameter and sends a pass message with 204 response if a success else a 404 if  there is a failure
